name: "NIX"

on:
  pull_request:
  push:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (clean environment)
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
      - name: Use Nix (flakes, nixpkgs-unstable)
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check flake evaluation
        run: nix flake check -v --show-trace --no-update-lock-file
