name: "Tests"

on:
  pull_request:
  push:

jobs:
  tests:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
      - name: Install Nix (flakes, nixpkgs-unstable)
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Check flake
        run: nix flake check -v --show-trace --no-update-lock-file
      - name: Build Project
        run: nix build . --no-link --show-trace --no-update-lock-file
